language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
script:
  - cd test-derive-diff && cargo build --verbose && cargo test --verbose
  - cd ../slog-struct-diff && cargo build --verbose && cargo test --verbose
